apiVersion: batch/v1
kind: CronJob
metadata:
  name: ellahthomas-job
  namespace: uvasds-services
spec:
  schedule: "0,30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ellahthomas-job-container
              image: ghcr.io/ellahthomas/iss-demo:latest
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: ds2002-mongo
              resources:
                limits:
                  cpu: "0.25"
                  memory: 512Mi
                requests:
                  cpu: "0.1"
                  memory: 256Mi
          restartPolicy: Never
  ttlSecondsAfterFinished: 86400

